-- psql -d voc4u -f initdata/init.sql
drop table word;
drop table image;
drop table link;

CREATE TABLE link (
    -- link id
    lid INTEGER UNIQUE NOT NULL
);




CREATE TABLE word (
    lang CHAR(2) NOT NULL,
    word TEXT NOT NULL,
    link INTEGER,
    FOREIGN KEY (link) REFERENCES link (lid),
    history SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY(lang, link)
);


CREATE TABLE image (
    image VARCHAR(255),
    link INTEGER,
    FOREIGN KEY (link) REFERENCES link (lid),
    history SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY(link)
);


-- http://tools.perceptus.ca/text-wiz.php

INSERT INTO link (lid) VALUES ('1');
INSERT INTO link (lid) VALUES ('2');
INSERT INTO link (lid) VALUES ('3');
INSERT INTO link (lid) VALUES ('4');
INSERT INTO link (lid) VALUES ('5');
INSERT INTO link (lid) VALUES ('6');
INSERT INTO link (lid) VALUES ('7');
INSERT INTO link (lid) VALUES ('8');
INSERT INTO link (lid) VALUES ('9');
INSERT INTO link (lid) VALUES ('10');
INSERT INTO link (lid) VALUES ('11');
INSERT INTO link (lid) VALUES ('12');
INSERT INTO link (lid) VALUES ('13');
INSERT INTO link (lid) VALUES ('14');
INSERT INTO link (lid) VALUES ('15');
INSERT INTO link (lid) VALUES ('16');
INSERT INTO link (lid) VALUES ('17');
INSERT INTO link (lid) VALUES ('18');
INSERT INTO link (lid) VALUES ('19');
INSERT INTO link (lid) VALUES ('20');
INSERT INTO link (lid) VALUES ('21');
INSERT INTO link (lid) VALUES ('22');
INSERT INTO link (lid) VALUES ('23');
INSERT INTO link (lid) VALUES ('24');
INSERT INTO link (lid) VALUES ('25');
INSERT INTO link (lid) VALUES ('26');
INSERT INTO link (lid) VALUES ('27');
INSERT INTO link (lid) VALUES ('28');
INSERT INTO link (lid) VALUES ('29');
INSERT INTO link (lid) VALUES ('30');
INSERT INTO link (lid) VALUES ('31');
INSERT INTO link (lid) VALUES ('32');
INSERT INTO link (lid) VALUES ('33');
INSERT INTO link (lid) VALUES ('34');
INSERT INTO link (lid) VALUES ('35');
INSERT INTO link (lid) VALUES ('36');
INSERT INTO link (lid) VALUES ('37');
INSERT INTO link (lid) VALUES ('38');
INSERT INTO link (lid) VALUES ('39');
INSERT INTO link (lid) VALUES ('40');
INSERT INTO link (lid) VALUES ('41');
INSERT INTO link (lid) VALUES ('42');
INSERT INTO link (lid) VALUES ('43');
INSERT INTO link (lid) VALUES ('44');
INSERT INTO link (lid) VALUES ('45');
INSERT INTO link (lid) VALUES ('46');
INSERT INTO link (lid) VALUES ('47');
INSERT INTO link (lid) VALUES ('48');
INSERT INTO link (lid) VALUES ('49');
INSERT INTO link (lid) VALUES ('50');
INSERT INTO link (lid) VALUES ('51');
INSERT INTO link (lid) VALUES ('52');
INSERT INTO link (lid) VALUES ('53');
INSERT INTO link (lid) VALUES ('54');
INSERT INTO link (lid) VALUES ('55');
INSERT INTO link (lid) VALUES ('56');
INSERT INTO link (lid) VALUES ('57');
INSERT INTO link (lid) VALUES ('58');
INSERT INTO link (lid) VALUES ('59');
INSERT INTO link (lid) VALUES ('60');
INSERT INTO link (lid) VALUES ('61');
INSERT INTO link (lid) VALUES ('62');
INSERT INTO link (lid) VALUES ('63');
INSERT INTO link (lid) VALUES ('64');
INSERT INTO link (lid) VALUES ('65');
INSERT INTO link (lid) VALUES ('66');
INSERT INTO link (lid) VALUES ('67');
INSERT INTO link (lid) VALUES ('68');
INSERT INTO link (lid) VALUES ('69');
INSERT INTO link (lid) VALUES ('70');
INSERT INTO link (lid) VALUES ('71');
INSERT INTO link (lid) VALUES ('72');
INSERT INTO link (lid) VALUES ('73');
INSERT INTO link (lid) VALUES ('74');
INSERT INTO link (lid) VALUES ('75');
INSERT INTO link (lid) VALUES ('76');
INSERT INTO link (lid) VALUES ('77');
INSERT INTO link (lid) VALUES ('78');
INSERT INTO link (lid) VALUES ('79');
INSERT INTO link (lid) VALUES ('80');
INSERT INTO link (lid) VALUES ('81');
INSERT INTO link (lid) VALUES ('82');
INSERT INTO link (lid) VALUES ('83');
INSERT INTO link (lid) VALUES ('84');
INSERT INTO link (lid) VALUES ('85');
INSERT INTO link (lid) VALUES ('86');
INSERT INTO link (lid) VALUES ('87');
INSERT INTO link (lid) VALUES ('88');
INSERT INTO link (lid) VALUES ('89');
INSERT INTO link (lid) VALUES ('90');
INSERT INTO link (lid) VALUES ('91');
INSERT INTO link (lid) VALUES ('92');
INSERT INTO link (lid) VALUES ('93');
INSERT INTO link (lid) VALUES ('94');
INSERT INTO link (lid) VALUES ('95');
INSERT INTO link (lid) VALUES ('96');
INSERT INTO link (lid) VALUES ('97');
INSERT INTO link (lid) VALUES ('98');
INSERT INTO link (lid) VALUES ('99');
INSERT INTO link (lid) VALUES ('100');
INSERT INTO link (lid) VALUES ('101');
INSERT INTO link (lid) VALUES ('102');
INSERT INTO link (lid) VALUES ('103');
INSERT INTO link (lid) VALUES ('104');
INSERT INTO link (lid) VALUES ('105');
INSERT INTO link (lid) VALUES ('106');
INSERT INTO link (lid) VALUES ('107');
INSERT INTO link (lid) VALUES ('108');
INSERT INTO link (lid) VALUES ('109');
INSERT INTO link (lid) VALUES ('110');
INSERT INTO link (lid) VALUES ('111');
INSERT INTO link (lid) VALUES ('112');
INSERT INTO link (lid) VALUES ('113');
INSERT INTO link (lid) VALUES ('114');
INSERT INTO link (lid) VALUES ('115');
INSERT INTO link (lid) VALUES ('116');
INSERT INTO link (lid) VALUES ('117');
INSERT INTO link (lid) VALUES ('118');
INSERT INTO link (lid) VALUES ('119');
INSERT INTO link (lid) VALUES ('120');
INSERT INTO link (lid) VALUES ('121');
INSERT INTO link (lid) VALUES ('122');
INSERT INTO link (lid) VALUES ('123');
INSERT INTO link (lid) VALUES ('124');
INSERT INTO link (lid) VALUES ('125');
INSERT INTO link (lid) VALUES ('126');
INSERT INTO link (lid) VALUES ('127');
INSERT INTO link (lid) VALUES ('128');
INSERT INTO link (lid) VALUES ('129');
INSERT INTO link (lid) VALUES ('130');
INSERT INTO link (lid) VALUES ('131');
INSERT INTO link (lid) VALUES ('132');
INSERT INTO link (lid) VALUES ('133');
INSERT INTO link (lid) VALUES ('134');
INSERT INTO link (lid) VALUES ('135');
INSERT INTO link (lid) VALUES ('136');
INSERT INTO link (lid) VALUES ('137');
INSERT INTO link (lid) VALUES ('138');
INSERT INTO link (lid) VALUES ('139');
INSERT INTO link (lid) VALUES ('140');
INSERT INTO link (lid) VALUES ('141');
INSERT INTO link (lid) VALUES ('142');
INSERT INTO link (lid) VALUES ('143');
INSERT INTO link (lid) VALUES ('144');
INSERT INTO link (lid) VALUES ('145');
INSERT INTO link (lid) VALUES ('146');
INSERT INTO link (lid) VALUES ('147');
INSERT INTO link (lid) VALUES ('148');
INSERT INTO link (lid) VALUES ('149');
INSERT INTO link (lid) VALUES ('150');
INSERT INTO link (lid) VALUES ('151');
INSERT INTO link (lid) VALUES ('152');
INSERT INTO link (lid) VALUES ('153');
INSERT INTO link (lid) VALUES ('154');
INSERT INTO link (lid) VALUES ('155');
INSERT INTO link (lid) VALUES ('156');
INSERT INTO link (lid) VALUES ('157');
INSERT INTO link (lid) VALUES ('158');
INSERT INTO link (lid) VALUES ('159');
INSERT INTO link (lid) VALUES ('160');
INSERT INTO link (lid) VALUES ('161');
INSERT INTO link (lid) VALUES ('162');
INSERT INTO link (lid) VALUES ('163');
INSERT INTO link (lid) VALUES ('164');
INSERT INTO link (lid) VALUES ('165');
INSERT INTO link (lid) VALUES ('166');
INSERT INTO link (lid) VALUES ('167');
INSERT INTO link (lid) VALUES ('168');
INSERT INTO link (lid) VALUES ('169');
INSERT INTO link (lid) VALUES ('170');
INSERT INTO link (lid) VALUES ('171');
INSERT INTO link (lid) VALUES ('172');
INSERT INTO link (lid) VALUES ('173');
INSERT INTO link (lid) VALUES ('174');
INSERT INTO link (lid) VALUES ('175');
INSERT INTO link (lid) VALUES ('176');
INSERT INTO link (lid) VALUES ('177');
INSERT INTO link (lid) VALUES ('178');
INSERT INTO link (lid) VALUES ('179');
INSERT INTO link (lid) VALUES ('180');
INSERT INTO link (lid) VALUES ('181');
INSERT INTO link (lid) VALUES ('182');
INSERT INTO link (lid) VALUES ('183');
INSERT INTO link (lid) VALUES ('184');
INSERT INTO link (lid) VALUES ('185');
INSERT INTO link (lid) VALUES ('186');
INSERT INTO link (lid) VALUES ('187');
INSERT INTO link (lid) VALUES ('188');
INSERT INTO link (lid) VALUES ('189');
INSERT INTO link (lid) VALUES ('190');
INSERT INTO link (lid) VALUES ('191');
INSERT INTO link (lid) VALUES ('192');
INSERT INTO link (lid) VALUES ('193');
INSERT INTO link (lid) VALUES ('194');
INSERT INTO link (lid) VALUES ('195');
INSERT INTO link (lid) VALUES ('196');
INSERT INTO link (lid) VALUES ('197');
INSERT INTO link (lid) VALUES ('198');
INSERT INTO link (lid) VALUES ('199');
INSERT INTO link (lid) VALUES ('200');
INSERT INTO link (lid) VALUES ('201');
INSERT INTO link (lid) VALUES ('202');
INSERT INTO link (lid) VALUES ('203');
INSERT INTO link (lid) VALUES ('204');
INSERT INTO link (lid) VALUES ('205');
INSERT INTO link (lid) VALUES ('206');
INSERT INTO link (lid) VALUES ('207');
INSERT INTO link (lid) VALUES ('208');
INSERT INTO link (lid) VALUES ('209');
INSERT INTO link (lid) VALUES ('210');
INSERT INTO link (lid) VALUES ('211');
INSERT INTO link (lid) VALUES ('212');
INSERT INTO link (lid) VALUES ('213');
INSERT INTO link (lid) VALUES ('214');
INSERT INTO link (lid) VALUES ('215');
INSERT INTO link (lid) VALUES ('216');
INSERT INTO link (lid) VALUES ('217');
INSERT INTO link (lid) VALUES ('218');
INSERT INTO link (lid) VALUES ('219');
INSERT INTO link (lid) VALUES ('220');
INSERT INTO link (lid) VALUES ('221');
INSERT INTO link (lid) VALUES ('222');
INSERT INTO link (lid) VALUES ('223');
INSERT INTO link (lid) VALUES ('224');
INSERT INTO link (lid) VALUES ('225');
INSERT INTO link (lid) VALUES ('226');
INSERT INTO link (lid) VALUES ('227');
INSERT INTO link (lid) VALUES ('228');
INSERT INTO link (lid) VALUES ('229');
INSERT INTO link (lid) VALUES ('230');
INSERT INTO link (lid) VALUES ('231');
INSERT INTO link (lid) VALUES ('232');
INSERT INTO link (lid) VALUES ('233');
INSERT INTO link (lid) VALUES ('234');
INSERT INTO link (lid) VALUES ('235');
INSERT INTO link (lid) VALUES ('236');
INSERT INTO link (lid) VALUES ('237');
INSERT INTO link (lid) VALUES ('238');
INSERT INTO link (lid) VALUES ('239');
INSERT INTO link (lid) VALUES ('240');
INSERT INTO link (lid) VALUES ('241');
INSERT INTO link (lid) VALUES ('242');
INSERT INTO link (lid) VALUES ('243');
INSERT INTO link (lid) VALUES ('244');
INSERT INTO link (lid) VALUES ('245');
INSERT INTO link (lid) VALUES ('246');
INSERT INTO link (lid) VALUES ('247');
INSERT INTO link (lid) VALUES ('248');
INSERT INTO link (lid) VALUES ('249');
INSERT INTO link (lid) VALUES ('250');
INSERT INTO link (lid) VALUES ('251');
INSERT INTO link (lid) VALUES ('252');
INSERT INTO link (lid) VALUES ('253');
INSERT INTO link (lid) VALUES ('254');
INSERT INTO link (lid) VALUES ('255');
INSERT INTO link (lid) VALUES ('256');
INSERT INTO link (lid) VALUES ('257');
INSERT INTO link (lid) VALUES ('258');
INSERT INTO link (lid) VALUES ('259');
INSERT INTO link (lid) VALUES ('260');
INSERT INTO link (lid) VALUES ('261');
INSERT INTO link (lid) VALUES ('262');
INSERT INTO link (lid) VALUES ('263');
INSERT INTO link (lid) VALUES ('264');
INSERT INTO link (lid) VALUES ('265');
INSERT INTO link (lid) VALUES ('266');
INSERT INTO link (lid) VALUES ('267');
INSERT INTO link (lid) VALUES ('268');
INSERT INTO link (lid) VALUES ('269');
INSERT INTO link (lid) VALUES ('270');
INSERT INTO link (lid) VALUES ('271');
INSERT INTO link (lid) VALUES ('272');
INSERT INTO link (lid) VALUES ('273');
INSERT INTO link (lid) VALUES ('274');
INSERT INTO link (lid) VALUES ('275');
INSERT INTO link (lid) VALUES ('276');
INSERT INTO link (lid) VALUES ('277');
INSERT INTO link (lid) VALUES ('278');
INSERT INTO link (lid) VALUES ('279');
INSERT INTO link (lid) VALUES ('280');
INSERT INTO link (lid) VALUES ('281');
INSERT INTO link (lid) VALUES ('282');
INSERT INTO link (lid) VALUES ('283');
INSERT INTO link (lid) VALUES ('284');
INSERT INTO link (lid) VALUES ('285');
INSERT INTO link (lid) VALUES ('286');
INSERT INTO link (lid) VALUES ('287');
INSERT INTO link (lid) VALUES ('288');
INSERT INTO link (lid) VALUES ('289');
INSERT INTO link (lid) VALUES ('290');
INSERT INTO link (lid) VALUES ('291');
INSERT INTO link (lid) VALUES ('292');
INSERT INTO link (lid) VALUES ('293');
INSERT INTO link (lid) VALUES ('294');
INSERT INTO link (lid) VALUES ('295');
INSERT INTO link (lid) VALUES ('296');
INSERT INTO link (lid) VALUES ('297');
INSERT INTO link (lid) VALUES ('298');
INSERT INTO link (lid) VALUES ('299');
INSERT INTO link (lid) VALUES ('300');
INSERT INTO link (lid) VALUES ('301');
INSERT INTO link (lid) VALUES ('302');
INSERT INTO link (lid) VALUES ('303');
INSERT INTO link (lid) VALUES ('304');
INSERT INTO link (lid) VALUES ('305');
INSERT INTO link (lid) VALUES ('306');
INSERT INTO link (lid) VALUES ('307');
INSERT INTO link (lid) VALUES ('308');
INSERT INTO link (lid) VALUES ('309');
INSERT INTO link (lid) VALUES ('310');
INSERT INTO link (lid) VALUES ('311');

INSERT INTO word (link,word,lang) VALUES ('1','mientras','es');
INSERT INTO word (link,word,lang) VALUES ('2','joven','es');
INSERT INTO word (link,word,lang) VALUES ('3','aeropuerto','es');
INSERT INTO word (link,word,lang) VALUES ('4','todo','es');
INSERT INTO word (link,word,lang) VALUES ('5','de todos modos','es');
INSERT INTO word (link,word,lang) VALUES ('6','arquitecto','es');
INSERT INTO word (link,word,lang) VALUES ('7','atleta','es');
INSERT INTO word (link,word,lang) VALUES ('8','principio','es');
INSERT INTO word (link,word,lang) VALUES ('9','pedir prestado','es');
INSERT INTO word (link,word,lang) VALUES ('10','traer','es');
INSERT INTO word (link,word,lang) VALUES ('11','pastel','es');
INSERT INTO word (link,word,lang) VALUES ('12','charlar','es');
INSERT INTO word (link,word,lang) VALUES ('13','comprobar','es');
INSERT INTO word (link,word,lang) VALUES ('14','ajedrez','es');
INSERT INTO word (link,word,lang) VALUES ('15','bebida fría','es');
INSERT INTO word (link,word,lang) VALUES ('16','¡Vamos!','es');
INSERT INTO word (link,word,lang) VALUES ('17','comunicarse','es');
INSERT INTO word (link,word,lang) VALUES ('18','juegos de ordenador','es');
INSERT INTO word (link,word,lang) VALUES ('19','interminable','es');
INSERT INTO word (link,word,lang) VALUES ('20','discúlpeme','es');
INSERT INTO word (link,word,lang) VALUES ('21','flores','es');
INSERT INTO word (link,word,lang) VALUES ('22','pronóstico','es');
INSERT INTO word (link,word,lang) VALUES ('23','historia','es');
INSERT INTO word (link,word,lang) VALUES ('24','intérprete','es');
INSERT INTO word (link,word,lang) VALUES ('25','lista','es');
INSERT INTO word (link,word,lang) VALUES ('26','perdido','es');
INSERT INTO word (link,word,lang) VALUES ('27','hacer posible','es');
INSERT INTO word (link,word,lang) VALUES ('28','muchos más','es');
INSERT INTO word (link,word,lang) VALUES ('29','significar','es');
INSERT INTO word (link,word,lang) VALUES ('30','militar','es');
INSERT INTO word (link,word,lang) VALUES ('31','red','es');
INSERT INTO word (link,word,lang) VALUES ('32','la próxima vez','es');
INSERT INTO word (link,word,lang) VALUES ('33','norte','es');
INSERT INTO word (link,word,lang) VALUES ('34','de negocios','es');
INSERT INTO word (link,word,lang) VALUES ('35','pasaporte','es');
INSERT INTO word (link,word,lang) VALUES ('36','plano','es');
INSERT INTO word (link,word,lang) VALUES ('37','problema','es');
INSERT INTO word (link,word,lang) VALUES ('38','empujar','es');
INSERT INTO word (link,word,lang) VALUES ('39','montar','es');
INSERT INTO word (link,word,lang) VALUES ('40','Ruso','es');
INSERT INTO word (link,word,lang) VALUES ('41','despacio','es');
INSERT INTO word (link,word,lang) VALUES ('42','expendedor','es');
INSERT INTO word (link,word,lang) VALUES ('43','tractor','es');
INSERT INTO word (link,word,lang) VALUES ('44','Televisores rotos','es');
INSERT INTO word (link,word,lang) VALUES ('45','utilizar','es');
INSERT INTO word (link,word,lang) VALUES ('46','web','es');
INSERT INTO word (link,word,lang) VALUES ('47','sitio web','es');
INSERT INTO word (link,word,lang) VALUES ('48','mundial','es');
INSERT INTO word (link,word,lang) VALUES ('49','aerolíneas','es');
INSERT INTO word (link,word,lang) VALUES ('50','extranjero','es');
INSERT INTO word (link,word,lang) VALUES ('51','vivo','es');
INSERT INTO word (link,word,lang) VALUES ('52','asombroso','es');
INSERT INTO word (link,word,lang) VALUES ('53','se convirtió en','es');
INSERT INTO word (link,word,lang) VALUES ('54','convertirse en','es');
INSERT INTO word (link,word,lang) VALUES ('55','sopló','es');
INSERT INTO word (link,word,lang) VALUES ('56','hueso','es');
INSERT INTO word (link,word,lang) VALUES ('57','rompió','es');
INSERT INTO word (link,word,lang) VALUES ('58','traído','es');
INSERT INTO word (link,word,lang) VALUES ('59','vino','es');
INSERT INTO word (link,word,lang) VALUES ('60','capturado','es');
INSERT INTO word (link,word,lang) VALUES ('61','continente','es');
INSERT INTO word (link,word,lang) VALUES ('62','chocar','es');
INSERT INTO word (link,word,lang) VALUES ('63','crimen','es');
INSERT INTO word (link,word,lang) VALUES ('64','peligroso','es');
INSERT INTO word (link,word,lang) VALUES ('65','hizo','es');
INSERT INTO word (link,word,lang) VALUES ('66','no lo hizo','es');
INSERT INTO word (link,word,lang) VALUES ('67','final','es');
INSERT INTO word (link,word,lang) VALUES ('68','enorme','es');
INSERT INTO word (link,word,lang) VALUES ('69','escapar','es');
INSERT INTO word (link,word,lang) VALUES ('70','esperar','es');
INSERT INTO word (link,word,lang) VALUES ('71','explotar','es');
INSERT INTO word (link,word,lang) VALUES ('72','pies','es');
INSERT INTO word (link,word,lang) VALUES ('73','talar','es');
INSERT INTO word (link,word,lang) VALUES ('74','voló','es');
INSERT INTO word (link,word,lang) VALUES ('75','fundar','es');
INSERT INTO word (link,word,lang) VALUES ('76','susto','es');
INSERT INTO word (link,word,lang) VALUES ('77','dio','es');
INSERT INTO word (link,word,lang) VALUES ('78','pistola','es');
INSERT INTO word (link,word,lang) VALUES ('79','tiene','es');
INSERT INTO word (link,word,lang) VALUES ('80','tenido','es');
INSERT INTO word (link,word,lang) VALUES ('81','peluquero','es');
INSERT INTO word (link,word,lang) VALUES ('82','cabeza','es');
INSERT INTO word (link,word,lang) VALUES ('83','ataque del corazón','es');
INSERT INTO word (link,word,lang) VALUES ('84','helicóptero','es');
INSERT INTO word (link,word,lang) VALUES ('85','golpear','es');
INSERT INTO word (link,word,lang) VALUES ('86','Apuesto','es');
INSERT INTO word (link,word,lang) VALUES ('87','invitar','es');
INSERT INTO word (link,word,lang) VALUES ('88','tierra','es');
INSERT INTO word (link,word,lang) VALUES ('89','izquierda','es');
INSERT INTO word (link,word,lang) VALUES ('90','hecho','es');
INSERT INTO word (link,word,lang) VALUES ('91','mi culpa','es');
INSERT INTO word (link,word,lang) VALUES ('92','noticias','es');
INSERT INTO word (link,word,lang) VALUES ('93','encima','es');
INSERT INTO word (link,word,lang) VALUES ('94','paracaídas','es');
INSERT INTO word (link,word,lang) VALUES ('95','coche de policía','es');
INSERT INTO word (link,word,lang) VALUES ('96','premio','es');
INSERT INTO word (link,word,lang) VALUES ('97','poner','es');
INSERT INTO word (link,word,lang) VALUES ('98','corrió','es');
INSERT INTO word (link,word,lang) VALUES ('99','rata','es');
INSERT INTO word (link,word,lang) VALUES ('100','rescatar','es');
INSERT INTO word (link,word,lang) VALUES ('101','robo','es');
INSERT INTO word (link,word,lang) VALUES ('102','huir','es');
INSERT INTO word (link,word,lang) VALUES ('103','dijo','es');
INSERT INTO word (link,word,lang) VALUES ('104','se hundió','es');
INSERT INTO word (link,word,lang) VALUES ('105','sierra','es');
INSERT INTO word (link,word,lang) VALUES ('106','hundirse','es');
INSERT INTO word (link,word,lang) VALUES ('107','situación','es');
INSERT INTO word (link,word,lang) VALUES ('108','nieve','es');
INSERT INTO word (link,word,lang) VALUES ('109','resolver','es');
INSERT INTO word (link,word,lang) VALUES ('110','extraño','es');
INSERT INTO word (link,word,lang) VALUES ('111','sobrevivir a','es');
INSERT INTO word (link,word,lang) VALUES ('112','nadó','es');
INSERT INTO word (link,word,lang) VALUES ('113','ladrón','es');
INSERT INTO word (link,word,lang) VALUES ('114','arrojó','es');
INSERT INTO word (link,word,lang) VALUES ('115','tomó','es');
INSERT INTO word (link,word,lang) VALUES ('116','La presentadora de televisión','es');
INSERT INTO word (link,word,lang) VALUES ('117','Estudio de televisión','es');
INSERT INTO word (link,word,lang) VALUES ('118','inconsciente','es');
INSERT INTO word (link,word,lang) VALUES ('119','despertarse','es');
INSERT INTO word (link,word,lang) VALUES ('120','fue','es');
INSERT INTO word (link,word,lang) VALUES ('121','ganar','es');
INSERT INTO word (link,word,lang) VALUES ('122','despertó','es');
INSERT INTO word (link,word,lang) VALUES ('123','won','es');
INSERT INTO word (link,word,lang) VALUES ('124','que muchos','es');
INSERT INTO word (link,word,lang) VALUES ('125','Usted ve.','es');
INSERT INTO word (link,word,lang) VALUES ('126','pastel de manzana','es');
INSERT INTO word (link,word,lang) VALUES ('127','tocino','es');
INSERT INTO word (link,word,lang) VALUES ('128','proyecto de ley','es');
INSERT INTO word (link,word,lang) VALUES ('129','tarjeta de cumpleaños','es');
INSERT INTO word (link,word,lang) VALUES ('130','café negro','es');
INSERT INTO word (link,word,lang) VALUES ('131','hamburguesa','es');
INSERT INTO word (link,word,lang) VALUES ('132','zanahorias','es');
INSERT INTO word (link,word,lang) VALUES ('133','ciertamente','es');
INSERT INTO word (link,word,lang) VALUES ('134','pollo','es');
INSERT INTO word (link,word,lang) VALUES ('135','cóctel','es');
INSERT INTO word (link,word,lang) VALUES ('136','crema','es');
INSERT INTO word (link,word,lang) VALUES ('137','taza','es');
INSERT INTO word (link,word,lang) VALUES ('138','postre','es');
INSERT INTO word (link,word,lang) VALUES ('139','factura de la luz','es');
INSERT INTO word (link,word,lang) VALUES ('140','sabor','es');
INSERT INTO word (link,word,lang) VALUES ('141','papas fritas','es');
INSERT INTO word (link,word,lang) VALUES ('142','fruta','es');
INSERT INTO word (link,word,lang) VALUES ('143','generación','es');
INSERT INTO word (link,word,lang) VALUES ('144','abuelita','es');
INSERT INTO word (link,word,lang) VALUES ('145','Indio','es');
INSERT INTO word (link,word,lang) VALUES ('146','kilo','es');
INSERT INTO word (link,word,lang) VALUES ('147','lechuga','es');
INSERT INTO word (link,word,lang) VALUES ('148','plato principal','es');
INSERT INTO word (link,word,lang) VALUES ('149','carne','es');
INSERT INTO word (link,word,lang) VALUES ('150','agua mineral','es');
INSERT INTO word (link,word,lang) VALUES ('151','ensalada mezclada','es');
INSERT INTO word (link,word,lang) VALUES ('152','más antiguo','es');
INSERT INTO word (link,word,lang) VALUES ('153','orden','es');
INSERT INTO word (link,word,lang) VALUES ('154','chícharos','es');
INSERT INTO word (link,word,lang) VALUES ('155','tarjeta telefónica','es');
INSERT INTO word (link,word,lang) VALUES ('156','palomitas de maíz','es');
INSERT INTO word (link,word,lang) VALUES ('157','patata','es');
INSERT INTO word (link,word,lang) VALUES ('158','programa','es');
INSERT INTO word (link,word,lang) VALUES ('159','rojo','es');
INSERT INTO word (link,word,lang) VALUES ('160','asado','es');
INSERT INTO word (link,word,lang) VALUES ('161','tamaño','es');
INSERT INTO word (link,word,lang) VALUES ('162','solo','es');
INSERT INTO word (link,word,lang) VALUES ('163','medio','es');
INSERT INTO word (link,word,lang) VALUES ('164','agua sin gas','es');
INSERT INTO word (link,word,lang) VALUES ('165','agua gaseosa','es');
INSERT INTO word (link,word,lang) VALUES ('166','prueba','es');
INSERT INTO word (link,word,lang) VALUES ('167','tomate','es');
INSERT INTO word (link,word,lang) VALUES ('168','esta noche','es');
INSERT INTO word (link,word,lang) VALUES ('169','vainilla','es');
INSERT INTO word (link,word,lang) VALUES ('170','vegetal','es');
INSERT INTO word (link,word,lang) VALUES ('171','café con leche','es');
INSERT INTO word (link,word,lang) VALUES ('172','¡Por supuesto!','es');
INSERT INTO word (link,word,lang) VALUES ('173','actriz','es');
INSERT INTO word (link,word,lang) VALUES ('174','aventura','es');
INSERT INTO word (link,word,lang) VALUES ('175','nadie','es');
INSERT INTO word (link,word,lang) VALUES ('176','','es');
INSERT INTO word (link,word,lang) VALUES ('177','mal','es');
INSERT INTO word (link,word,lang) VALUES ('178','creer','es');
INSERT INTO word (link,word,lang) VALUES ('179','culturista','es');
INSERT INTO word (link,word,lang) VALUES ('180','culturismo','es');
INSERT INTO word (link,word,lang) VALUES ('181','nacido','es');
INSERT INTO word (link,word,lang) VALUES ('182','valiente','es');
INSERT INTO word (link,word,lang) VALUES ('183','valientemente','es');
INSERT INTO word (link,word,lang) VALUES ('184','comedia','es');
INSERT INTO word (link,word,lang) VALUES ('185','salir','es');
INSERT INTO word (link,word,lang) VALUES ('186','concierto','es');
INSERT INTO word (link,word,lang) VALUES ('187','fácilmente','es');
INSERT INTO word (link,word,lang) VALUES ('188','fácil','es');
INSERT INTO word (link,word,lang) VALUES ('189','suficiente','es');
INSERT INTO word (link,word,lang) VALUES ('190','episodio','es');
INSERT INTO word (link,word,lang) VALUES ('191','emocionante','es');
INSERT INTO word (link,word,lang) VALUES ('192','luchar','es');
INSERT INTO word (link,word,lang) VALUES ('193','primero','es');
INSERT INTO word (link,word,lang) VALUES ('194','seguir','es');
INSERT INTO word (link,word,lang) VALUES ('195','luchado','es');
INSERT INTO word (link,word,lang) VALUES ('196','duro','es');
INSERT INTO word (link,word,lang) VALUES ('197','fuertemente','es');
INSERT INTO word (link,word,lang) VALUES ('198','patear','es');
INSERT INTO word (link,word,lang) VALUES ('199','local','es');
INSERT INTO word (link,word,lang) VALUES ('200','en voz alta','es');
INSERT INTO word (link,word,lang) VALUES ('201','modesto','es');
INSERT INTO word (link,word,lang) VALUES ('202','cuello','es');
INSERT INTO word (link,word,lang) VALUES ('203','rápidamente','es');
INSERT INTO word (link,word,lang) VALUES ('204','tranquilamente','es');
INSERT INTO word (link,word,lang) VALUES ('205','razón','es');
INSERT INTO word (link,word,lang) VALUES ('206','reportero','es');
INSERT INTO word (link,word,lang) VALUES ('207','robot','es');
INSERT INTO word (link,word,lang) VALUES ('208','con tristeza','es');
INSERT INTO word (link,word,lang) VALUES ('209','guardar','es');
INSERT INTO word (link,word,lang) VALUES ('210','ciencia ficción','es');
INSERT INTO word (link,word,lang) VALUES ('211','en segundo lugar','es');
INSERT INTO word (link,word,lang) VALUES ('212','velocímetro','es');
INSERT INTO word (link,word,lang) VALUES ('213','especialista','es');
INSERT INTO word (link,word,lang) VALUES ('214','en tercer lugar','es');
INSERT INTO word (link,word,lang) VALUES ('215','a la estrella','es');
INSERT INTO word (link,word,lang) VALUES ('216','girar','es');
INSERT INTO word (link,word,lang) VALUES ('217','desabrochar','es');
INSERT INTO word (link,word,lang) VALUES ('218','palabra','es');
INSERT INTO word (link,word,lang) VALUES ('219','años','es');
INSERT INTO word (link,word,lang) VALUES ('220','barbacoa','es');
INSERT INTO word (link,word,lang) VALUES ('221','bota','es');
INSERT INTO word (link,word,lang) VALUES ('222','Día de Navidad','es');
INSERT INTO word (link,word,lang) VALUES ('223','durante','es');
INSERT INTO word (link,word,lang) VALUES ('224','disfrutar','es');
INSERT INTO word (link,word,lang) VALUES ('225','desfile de moda','es');
INSERT INTO word (link,word,lang) VALUES ('226','casarse','es');
INSERT INTO word (link,word,lang) VALUES ('227','prepararse','es');
INSERT INTO word (link,word,lang) VALUES ('228','hambriento','es');
INSERT INTO word (link,word,lang) VALUES ('229','oyentes','es');
INSERT INTO word (link,word,lang) VALUES ('230','historia de amor','es');
INSERT INTO word (link,word,lang) VALUES ('231','satisfacer','es');
INSERT INTO word (link,word,lang) VALUES ('232','modelo','es');
INSERT INTO word (link,word,lang) VALUES ('233','empacar bolsas','es');
INSERT INTO word (link,word,lang) VALUES ('234','lluvia','es');
INSERT INTO word (link,word,lang) VALUES ('235','sandalia','es');
INSERT INTO word (link,word,lang) VALUES ('236','calcetín','es');
INSERT INTO word (link,word,lang) VALUES ('237','especial','es');
INSERT INTO word (link,word,lang) VALUES ('238','traje de baño','es');
INSERT INTO word (link,word,lang) VALUES ('239','las noticias','es');
INSERT INTO word (link,word,lang) VALUES ('240','sediento','es');
INSERT INTO word (link,word,lang) VALUES ('241','cansado','es');
INSERT INTO word (link,word,lang) VALUES ('242','argumento','es');
INSERT INTO word (link,word,lang) VALUES ('243','bat','es');
INSERT INTO word (link,word,lang) VALUES ('244','compañero de negocios','es');
INSERT INTO word (link,word,lang) VALUES ('245','soltar','es');
INSERT INTO word (link,word,lang) VALUES ('246','huellas dactilares','es');
INSERT INTO word (link,word,lang) VALUES ('247','manejar','es');
INSERT INTO word (link,word,lang) VALUES ('248','oído','es');
INSERT INTO word (link,word,lang) VALUES ('249','conocido','es');
INSERT INTO word (link,word,lang) VALUES ('250','asesinato','es');
INSERT INTO word (link,word,lang) VALUES ('251','asesino','es');
INSERT INTO word (link,word,lang) VALUES ('252','sospechar','es');
INSERT INTO word (link,word,lang) VALUES ('253','mujer','es');
INSERT INTO word (link,word,lang) VALUES ('254','alrededor','es');
INSERT INTO word (link,word,lang) VALUES ('255','adulto','es');
INSERT INTO word (link,word,lang) VALUES ('256','Círculo Polar Ártico','es');
INSERT INTO word (link,word,lang) VALUES ('257','bicicleta','es');
INSERT INTO word (link,word,lang) VALUES ('258','recorrido en autobús','es');
INSERT INTO word (link,word,lang) VALUES ('259','ocupado','es');
INSERT INTO word (link,word,lang) VALUES ('260','costo','es');
INSERT INTO word (link,word,lang) VALUES ('261','diario','es');
INSERT INTO word (link,word,lang) VALUES ('262','excitado','es');
INSERT INTO word (link,word,lang) VALUES ('263','vuelo','es');
INSERT INTO word (link,word,lang) VALUES ('264','volar','es');
INSERT INTO word (link,word,lang) VALUES ('265','futuro','es');
INSERT INTO word (link,word,lang) VALUES ('266','salir a correr','es');
INSERT INTO word (link,word,lang) VALUES ('267','hacer turismo','es');
INSERT INTO word (link,word,lang) VALUES ('268','albergue','es');
INSERT INTO word (link,word,lang) VALUES ('269','mes pasado','es');
INSERT INTO word (link,word,lang) VALUES ('270','afortunado','es');
INSERT INTO word (link,word,lang) VALUES ('271','moto','es');
INSERT INTO word (link,word,lang) VALUES ('272','Nueva Zelandia','es');
INSERT INTO word (link,word,lang) VALUES ('273','plan','es');
INSERT INTO word (link,word,lang) VALUES ('274','mochila','es');
INSERT INTO word (link,word,lang) VALUES ('275','enviar','es');
INSERT INTO word (link,word,lang) VALUES ('276','maleta','es');
INSERT INTO word (link,word,lang) VALUES ('277','agente de viaje','es');
INSERT INTO word (link,word,lang) VALUES ('278','Subterráneo','es');
INSERT INTO word (link,word,lang) VALUES ('279','vía','es');
INSERT INTO word (link,word,lang) VALUES ('280','','es');
INSERT INTO word (link,word,lang) VALUES ('281','por todo el mundo','es');
INSERT INTO word (link,word,lang) VALUES ('282','ministerio de defensa','es');
INSERT INTO word (link,word,lang) VALUES ('283','no importa','es');
INSERT INTO word (link,word,lang) VALUES ('284','no funciona','es');
INSERT INTO word (link,word,lang) VALUES ('285','Dime la vez, por favor.','es');
INSERT INTO word (link,word,lang) VALUES ('286','espere un minuto','es');
INSERT INTO word (link,word,lang) VALUES ('287','al mismo tiempo','es');
INSERT INTO word (link,word,lang) VALUES ('288','cambiar de opinión','es');
INSERT INTO word (link,word,lang) VALUES ('289','a mediados de','es');
INSERT INTO word (link,word,lang) VALUES ('290','en su camino de ... a','es');
INSERT INTO word (link,word,lang) VALUES ('291','¿Qué está pasando?','es');
INSERT INTO word (link,word,lang) VALUES ('292','sentirse como en casa','es');
INSERT INTO word (link,word,lang) VALUES ('293','Aquí tiene.','es');
INSERT INTO word (link,word,lang) VALUES ('294','Sólo estoy buscando','es');
INSERT INTO word (link,word,lang) VALUES ('295','junto a la orilla','es');
INSERT INTO word (link,word,lang) VALUES ('296','vaqueros','es');
INSERT INTO word (link,word,lang) VALUES ('297','¿De qué tamaño es usted?','es');
INSERT INTO word (link,word,lang) VALUES ('298','¿Quieres ...?','es');
INSERT INTO word (link,word,lang) VALUES ('299','ahora mismo','es');
INSERT INTO word (link,word,lang) VALUES ('300','¿De qué color es?','es');
INSERT INTO word (link,word,lang) VALUES ('301','coger un avión','es');
INSERT INTO word (link,word,lang) VALUES ('302','¿hasta cuándo?','es');
INSERT INTO word (link,word,lang) VALUES ('303','es el momento de ir','es');
INSERT INTO word (link,word,lang) VALUES ('304','la siguiente','es');


INSERT INTO word (link,word,lang) VALUES ('1','zatímco','cs');
INSERT INTO word (link,word,lang) VALUES ('2','mladý','cs');
INSERT INTO word (link,word,lang) VALUES ('3','letiště','cs');
INSERT INTO word (link,word,lang) VALUES ('4','vše','cs');
INSERT INTO word (link,word,lang) VALUES ('5','stejně','cs');
INSERT INTO word (link,word,lang) VALUES ('6','architekt','cs');
INSERT INTO word (link,word,lang) VALUES ('7','sportovec','cs');
INSERT INTO word (link,word,lang) VALUES ('8','začátek','cs');
INSERT INTO word (link,word,lang) VALUES ('9','půjčit si','cs');
INSERT INTO word (link,word,lang) VALUES ('10','přinést','cs');
INSERT INTO word (link,word,lang) VALUES ('11','dort','cs');
INSERT INTO word (link,word,lang) VALUES ('12','povídat','cs');
INSERT INTO word (link,word,lang) VALUES ('13','kontrola','cs');
INSERT INTO word (link,word,lang) VALUES ('14','šachy','cs');
INSERT INTO word (link,word,lang) VALUES ('15','studený nápoj','cs');
INSERT INTO word (link,word,lang) VALUES ('16','Tak pojď!','cs');
INSERT INTO word (link,word,lang) VALUES ('17','komunikovat','cs');
INSERT INTO word (link,word,lang) VALUES ('18','počítačové hry','cs');
INSERT INTO word (link,word,lang) VALUES ('19','nekonečný','cs');
INSERT INTO word (link,word,lang) VALUES ('20','promiňte','cs');
INSERT INTO word (link,word,lang) VALUES ('21','květiny','cs');
INSERT INTO word (link,word,lang) VALUES ('22','předpověď','cs');
INSERT INTO word (link,word,lang) VALUES ('23','historie','cs');
INSERT INTO word (link,word,lang) VALUES ('24','tlumočník','cs');
INSERT INTO word (link,word,lang) VALUES ('25','seznam','cs');
INSERT INTO word (link,word,lang) VALUES ('26','ztracený','cs');
INSERT INTO word (link,word,lang) VALUES ('27','umožňují','cs');
INSERT INTO word (link,word,lang) VALUES ('28','mnoho dalších','cs');
INSERT INTO word (link,word,lang) VALUES ('29','průměr','cs');
INSERT INTO word (link,word,lang) VALUES ('30','vojenský','cs');
INSERT INTO word (link,word,lang) VALUES ('31','síť','cs');
INSERT INTO word (link,word,lang) VALUES ('32','příště','cs');
INSERT INTO word (link,word,lang) VALUES ('33','sever','cs');
INSERT INTO word (link,word,lang) VALUES ('34','na podnikání','cs');
INSERT INTO word (link,word,lang) VALUES ('35','pas','cs');
INSERT INTO word (link,word,lang) VALUES ('36','rovina','cs');
INSERT INTO word (link,word,lang) VALUES ('37','problém','cs');
INSERT INTO word (link,word,lang) VALUES ('38','tlačit','cs');
INSERT INTO word (link,word,lang) VALUES ('39','jízda','cs');
INSERT INTO word (link,word,lang) VALUES ('40','Ruština','cs');
INSERT INTO word (link,word,lang) VALUES ('41','pomalu','cs');
INSERT INTO word (link,word,lang) VALUES ('42','parkovací automaty','cs');
INSERT INTO word (link,word,lang) VALUES ('43','traktor','cs');
INSERT INTO word (link,word,lang) VALUES ('44','Televizory zlomené','cs');
INSERT INTO word (link,word,lang) VALUES ('45','použití','cs');
INSERT INTO word (link,word,lang) VALUES ('46','web','cs');
INSERT INTO word (link,word,lang) VALUES ('47','webové stránky','cs');
INSERT INTO word (link,word,lang) VALUES ('48','celosvětově','cs');
INSERT INTO word (link,word,lang) VALUES ('49','letecké společnosti','cs');
INSERT INTO word (link,word,lang) VALUES ('50','cizí','cs');
INSERT INTO word (link,word,lang) VALUES ('51','naživu','cs');
INSERT INTO word (link,word,lang) VALUES ('52','úžasný','cs');
INSERT INTO word (link,word,lang) VALUES ('53','se stal','cs');
INSERT INTO word (link,word,lang) VALUES ('54','stát se','cs');
INSERT INTO word (link,word,lang) VALUES ('55','foukal','cs');
INSERT INTO word (link,word,lang) VALUES ('56','kost','cs');
INSERT INTO word (link,word,lang) VALUES ('57','zlomil','cs');
INSERT INTO word (link,word,lang) VALUES ('58','přinesl','cs');
INSERT INTO word (link,word,lang) VALUES ('59','přišel','cs');
INSERT INTO word (link,word,lang) VALUES ('60','chytil','cs');
INSERT INTO word (link,word,lang) VALUES ('61','kontinent','cs');
INSERT INTO word (link,word,lang) VALUES ('62','pád','cs');
INSERT INTO word (link,word,lang) VALUES ('63','zločin','cs');
INSERT INTO word (link,word,lang) VALUES ('64','nebezpečný','cs');
INSERT INTO word (link,word,lang) VALUES ('65','ano','cs');
INSERT INTO word (link,word,lang) VALUES ('66','ne','cs');
INSERT INTO word (link,word,lang) VALUES ('67','konec','cs');
INSERT INTO word (link,word,lang) VALUES ('68','obrovský','cs');
INSERT INTO word (link,word,lang) VALUES ('69','uniknout','cs');
INSERT INTO word (link,word,lang) VALUES ('70','očekávat','cs');
INSERT INTO word (link,word,lang) VALUES ('71','explodovat','cs');
INSERT INTO word (link,word,lang) VALUES ('72','nohy','cs');
INSERT INTO word (link,word,lang) VALUES ('73','klesl','cs');
INSERT INTO word (link,word,lang) VALUES ('74','letěl','cs');
INSERT INTO word (link,word,lang) VALUES ('75','nalezeno','cs');
INSERT INTO word (link,word,lang) VALUES ('76','hrůza','cs');
INSERT INTO word (link,word,lang) VALUES ('77','dal','cs');
INSERT INTO word (link,word,lang) VALUES ('78','pistole','cs');
INSERT INTO word (link,word,lang) VALUES ('79','dostal','cs');
INSERT INTO word (link,word,lang) VALUES ('80','měl','cs');
INSERT INTO word (link,word,lang) VALUES ('81','kadeřník','cs');
INSERT INTO word (link,word,lang) VALUES ('82','hlava','cs');
INSERT INTO word (link,word,lang) VALUES ('83','infarkt','cs');
INSERT INTO word (link,word,lang) VALUES ('84','vrtulník','cs');
INSERT INTO word (link,word,lang) VALUES ('85','hit','cs');
INSERT INTO word (link,word,lang) VALUES ('86','Vsadím se, že','cs');
INSERT INTO word (link,word,lang) VALUES ('87','pozvat','cs');
INSERT INTO word (link,word,lang) VALUES ('88','země','cs');
INSERT INTO word (link,word,lang) VALUES ('89','vlevo','cs');
INSERT INTO word (link,word,lang) VALUES ('90','vyrobený','cs');
INSERT INTO word (link,word,lang) VALUES ('91','moje chyba','cs');
INSERT INTO word (link,word,lang) VALUES ('92','zprávy','cs');
INSERT INTO word (link,word,lang) VALUES ('93','přes','cs');
INSERT INTO word (link,word,lang) VALUES ('94','padák','cs');
INSERT INTO word (link,word,lang) VALUES ('95','policejní auto','cs');
INSERT INTO word (link,word,lang) VALUES ('96','cena','cs');
INSERT INTO word (link,word,lang) VALUES ('97','obléci','cs');
INSERT INTO word (link,word,lang) VALUES ('98','běžel','cs');
INSERT INTO word (link,word,lang) VALUES ('99','krysa','cs');
INSERT INTO word (link,word,lang) VALUES ('100','zachránit','cs');
INSERT INTO word (link,word,lang) VALUES ('101','loupež','cs');
INSERT INTO word (link,word,lang) VALUES ('102','utéci','cs');
INSERT INTO word (link,word,lang) VALUES ('103','uvedený','cs');
INSERT INTO word (link,word,lang) VALUES ('104','potopila','cs');
INSERT INTO word (link,word,lang) VALUES ('105','viděl','cs');
INSERT INTO word (link,word,lang) VALUES ('106','dřez','cs');
INSERT INTO word (link,word,lang) VALUES ('107','situace','cs');
INSERT INTO word (link,word,lang) VALUES ('108','sníh','cs');
INSERT INTO word (link,word,lang) VALUES ('109','vyřešit','cs');
INSERT INTO word (link,word,lang) VALUES ('110','zvláštní','cs');
INSERT INTO word (link,word,lang) VALUES ('111','přežít','cs');
INSERT INTO word (link,word,lang) VALUES ('112','plaval','cs');
INSERT INTO word (link,word,lang) VALUES ('113','zloděj','cs');
INSERT INTO word (link,word,lang) VALUES ('114','hodil','cs');
INSERT INTO word (link,word,lang) VALUES ('115','se','cs');
INSERT INTO word (link,word,lang) VALUES ('116','Televizní moderátorka','cs');
INSERT INTO word (link,word,lang) VALUES ('117','TV studio','cs');
INSERT INTO word (link,word,lang) VALUES ('118','v bezvědomí','cs');
INSERT INTO word (link,word,lang) VALUES ('119','vzbudit','cs');
INSERT INTO word (link,word,lang) VALUES ('120','šel','cs');
INSERT INTO word (link,word,lang) VALUES ('121','vítězství','cs');
INSERT INTO word (link,word,lang) VALUES ('122','Probudil','cs');
INSERT INTO word (link,word,lang) VALUES ('123','vyhrál','cs');
INSERT INTO word (link,word,lang) VALUES ('124','bando','cs');
INSERT INTO word (link,word,lang) VALUES ('125','Vidíte.','cs');
INSERT INTO word (link,word,lang) VALUES ('126','jablečný koláč','cs');
INSERT INTO word (link,word,lang) VALUES ('127','slanina','cs');
INSERT INTO word (link,word,lang) VALUES ('128','účet','cs');
INSERT INTO word (link,word,lang) VALUES ('129','blahopřání k narozeninám','cs');
INSERT INTO word (link,word,lang) VALUES ('130','černá káva','cs');
INSERT INTO word (link,word,lang) VALUES ('131','hamburger','cs');
INSERT INTO word (link,word,lang) VALUES ('132','mrkev','cs');
INSERT INTO word (link,word,lang) VALUES ('133','jistě','cs');
INSERT INTO word (link,word,lang) VALUES ('134','kuře','cs');
INSERT INTO word (link,word,lang) VALUES ('135','koktejl','cs');
INSERT INTO word (link,word,lang) VALUES ('136','krém','cs');
INSERT INTO word (link,word,lang) VALUES ('137','šálek','cs');
INSERT INTO word (link,word,lang) VALUES ('138','dezert','cs');
INSERT INTO word (link,word,lang) VALUES ('139','elektřinu','cs');
INSERT INTO word (link,word,lang) VALUES ('140','příchuť','cs');
INSERT INTO word (link,word,lang) VALUES ('141','hranolky','cs');
INSERT INTO word (link,word,lang) VALUES ('142','ovoce','cs');
INSERT INTO word (link,word,lang) VALUES ('143','generace','cs');
INSERT INTO word (link,word,lang) VALUES ('144','babička','cs');
INSERT INTO word (link,word,lang) VALUES ('145','Indický','cs');
INSERT INTO word (link,word,lang) VALUES ('146','kilo','cs');
INSERT INTO word (link,word,lang) VALUES ('147','salát','cs');
INSERT INTO word (link,word,lang) VALUES ('148','hlavní chod','cs');
INSERT INTO word (link,word,lang) VALUES ('149','maso','cs');
INSERT INTO word (link,word,lang) VALUES ('150','minerálka','cs');
INSERT INTO word (link,word,lang) VALUES ('151','míchaný salát','cs');
INSERT INTO word (link,word,lang) VALUES ('152','Nejstarší','cs');
INSERT INTO word (link,word,lang) VALUES ('153','objednávka','cs');
INSERT INTO word (link,word,lang) VALUES ('154','hrášek','cs');
INSERT INTO word (link,word,lang) VALUES ('155','telefonní karta','cs');
INSERT INTO word (link,word,lang) VALUES ('156','pražená kukuřice','cs');
INSERT INTO word (link,word,lang) VALUES ('157','brambor','cs');
INSERT INTO word (link,word,lang) VALUES ('158','program','cs');
INSERT INTO word (link,word,lang) VALUES ('159','červený','cs');
INSERT INTO word (link,word,lang) VALUES ('160','pečeně','cs');
INSERT INTO word (link,word,lang) VALUES ('161','velikost','cs');
INSERT INTO word (link,word,lang) VALUES ('162','jednolůžkový','cs');
INSERT INTO word (link,word,lang) VALUES ('163','střední','cs');
INSERT INTO word (link,word,lang) VALUES ('164','neperlivá voda','cs');
INSERT INTO word (link,word,lang) VALUES ('165','perlivá voda','cs');
INSERT INTO word (link,word,lang) VALUES ('166','test','cs');
INSERT INTO word (link,word,lang) VALUES ('167','rajče','cs');
INSERT INTO word (link,word,lang) VALUES ('168','dnes večer','cs');
INSERT INTO word (link,word,lang) VALUES ('169','vanilka','cs');
INSERT INTO word (link,word,lang) VALUES ('170','zeleninový','cs');
INSERT INTO word (link,word,lang) VALUES ('171','bílá káva','cs');
INSERT INTO word (link,word,lang) VALUES ('172','můžete vsadit!','cs');
INSERT INTO word (link,word,lang) VALUES ('173','herečka','cs');
INSERT INTO word (link,word,lang) VALUES ('174','dobrodružství','cs');
INSERT INTO word (link,word,lang) VALUES ('175','někdo','cs');
INSERT INTO word (link,word,lang) VALUES ('176','','cs');
INSERT INTO word (link,word,lang) VALUES ('177','špatně','cs');
INSERT INTO word (link,word,lang) VALUES ('178','věřit','cs');
INSERT INTO word (link,word,lang) VALUES ('179','kulturista','cs');
INSERT INTO word (link,word,lang) VALUES ('180','kulturistika','cs');
INSERT INTO word (link,word,lang) VALUES ('181','narozený','cs');
INSERT INTO word (link,word,lang) VALUES ('182','statečný','cs');
INSERT INTO word (link,word,lang) VALUES ('183','statečně','cs');
INSERT INTO word (link,word,lang) VALUES ('184','komedie','cs');
INSERT INTO word (link,word,lang) VALUES ('185','odejít','cs');
INSERT INTO word (link,word,lang) VALUES ('186','koncert','cs');
INSERT INTO word (link,word,lang) VALUES ('187','snadno','cs');
INSERT INTO word (link,word,lang) VALUES ('188','snadný','cs');
INSERT INTO word (link,word,lang) VALUES ('189','dost','cs');
INSERT INTO word (link,word,lang) VALUES ('190','epizoda','cs');
INSERT INTO word (link,word,lang) VALUES ('191','vzrušující','cs');
INSERT INTO word (link,word,lang) VALUES ('192','bojovat','cs');
INSERT INTO word (link,word,lang) VALUES ('193','za prvé','cs');
INSERT INTO word (link,word,lang) VALUES ('194','následovat','cs');
INSERT INTO word (link,word,lang) VALUES ('195','Bojoval','cs');
INSERT INTO word (link,word,lang) VALUES ('196','těžce','cs');
INSERT INTO word (link,word,lang) VALUES ('197','silně','cs');
INSERT INTO word (link,word,lang) VALUES ('198','kopat','cs');
INSERT INTO word (link,word,lang) VALUES ('199','místní','cs');
INSERT INTO word (link,word,lang) VALUES ('200','hlasitě','cs');
INSERT INTO word (link,word,lang) VALUES ('201','skromný','cs');
INSERT INTO word (link,word,lang) VALUES ('202','krk','cs');
INSERT INTO word (link,word,lang) VALUES ('203','rychle','cs');
INSERT INTO word (link,word,lang) VALUES ('204','klidně','cs');
INSERT INTO word (link,word,lang) VALUES ('205','důvod','cs');
INSERT INTO word (link,word,lang) VALUES ('206','reportér','cs');
INSERT INTO word (link,word,lang) VALUES ('207','robot','cs');
INSERT INTO word (link,word,lang) VALUES ('208','smutně','cs');
INSERT INTO word (link,word,lang) VALUES ('209','uložit','cs');
INSERT INTO word (link,word,lang) VALUES ('210','sci-fi','cs');
INSERT INTO word (link,word,lang) VALUES ('211','za druhé','cs');
INSERT INTO word (link,word,lang) VALUES ('212','rychloměr','cs');
INSERT INTO word (link,word,lang) VALUES ('213','kaskadér','cs');
INSERT INTO word (link,word,lang) VALUES ('214','za třetí','cs');
INSERT INTO word (link,word,lang) VALUES ('215','označit hvězdičkou','cs');
INSERT INTO word (link,word,lang) VALUES ('216','otočit se','cs');
INSERT INTO word (link,word,lang) VALUES ('217','rozepnout','cs');
INSERT INTO word (link,word,lang) VALUES ('218','slovo','cs');
INSERT INTO word (link,word,lang) VALUES ('219','let','cs');
INSERT INTO word (link,word,lang) VALUES ('220','grilování','cs');
INSERT INTO word (link,word,lang) VALUES ('221','bota','cs');
INSERT INTO word (link,word,lang) VALUES ('222','Štědrý den','cs');
INSERT INTO word (link,word,lang) VALUES ('223','během','cs');
INSERT INTO word (link,word,lang) VALUES ('224','těšit','cs');
INSERT INTO word (link,word,lang) VALUES ('225','módní přehlídka','cs');
INSERT INTO word (link,word,lang) VALUES ('226','vdávat','cs');
INSERT INTO word (link,word,lang) VALUES ('227','připravit','cs');
INSERT INTO word (link,word,lang) VALUES ('228','hladový','cs');
INSERT INTO word (link,word,lang) VALUES ('229','posluchači','cs');
INSERT INTO word (link,word,lang) VALUES ('230','milostný příběh','cs');
INSERT INTO word (link,word,lang) VALUES ('231','setkat se','cs');
INSERT INTO word (link,word,lang) VALUES ('232','model','cs');
INSERT INTO word (link,word,lang) VALUES ('233','sbalit kufry','cs');
INSERT INTO word (link,word,lang) VALUES ('234','déšť','cs');
INSERT INTO word (link,word,lang) VALUES ('235','sandál','cs');
INSERT INTO word (link,word,lang) VALUES ('236','ponožka','cs');
INSERT INTO word (link,word,lang) VALUES ('237','speciální','cs');
INSERT INTO word (link,word,lang) VALUES ('238','dámské plavky','cs');
INSERT INTO word (link,word,lang) VALUES ('239','novinky','cs');
INSERT INTO word (link,word,lang) VALUES ('240','žíznivý','cs');
INSERT INTO word (link,word,lang) VALUES ('241','unavený','cs');
INSERT INTO word (link,word,lang) VALUES ('242','argument','cs');
INSERT INTO word (link,word,lang) VALUES ('243','bat','cs');
INSERT INTO word (link,word,lang) VALUES ('244','obchodní partner','cs');
INSERT INTO word (link,word,lang) VALUES ('245','pokles','cs');
INSERT INTO word (link,word,lang) VALUES ('246','otisky prstů','cs');
INSERT INTO word (link,word,lang) VALUES ('247','rukojeť','cs');
INSERT INTO word (link,word,lang) VALUES ('248','slyšet','cs');
INSERT INTO word (link,word,lang) VALUES ('249','splněna','cs');
INSERT INTO word (link,word,lang) VALUES ('250','vražda','cs');
INSERT INTO word (link,word,lang) VALUES ('251','vrah','cs');
INSERT INTO word (link,word,lang) VALUES ('252','podezřelý','cs');
INSERT INTO word (link,word,lang) VALUES ('253','žena','cs');
INSERT INTO word (link,word,lang) VALUES ('254','kolem','cs');
INSERT INTO word (link,word,lang) VALUES ('255','dospělý','cs');
INSERT INTO word (link,word,lang) VALUES ('256','Arctic Circle','cs');
INSERT INTO word (link,word,lang) VALUES ('257','jízdní kolo','cs');
INSERT INTO word (link,word,lang) VALUES ('258','autobusem turné','cs');
INSERT INTO word (link,word,lang) VALUES ('259','zaneprázdněný','cs');
INSERT INTO word (link,word,lang) VALUES ('260','náklady','cs');
INSERT INTO word (link,word,lang) VALUES ('261','deník','cs');
INSERT INTO word (link,word,lang) VALUES ('262','vzrušený','cs');
INSERT INTO word (link,word,lang) VALUES ('263','','cs');
INSERT INTO word (link,word,lang) VALUES ('264','létat','cs');
INSERT INTO word (link,word,lang) VALUES ('265','budoucnost','cs');
INSERT INTO word (link,word,lang) VALUES ('266','jít běhat','cs');
INSERT INTO word (link,word,lang) VALUES ('267','prohlédnout pamětihodnosti','cs');
INSERT INTO word (link,word,lang) VALUES ('268','ubytovna','cs');
INSERT INTO word (link,word,lang) VALUES ('269','poslední měsíc','cs');
INSERT INTO word (link,word,lang) VALUES ('270','šťastný','cs');
INSERT INTO word (link,word,lang) VALUES ('271','motorka','cs');
INSERT INTO word (link,word,lang) VALUES ('272','Nový Zéland','cs');
INSERT INTO word (link,word,lang) VALUES ('273','plán','cs');
INSERT INTO word (link,word,lang) VALUES ('274','batoh','cs');
INSERT INTO word (link,word,lang) VALUES ('275','loď','cs');
INSERT INTO word (link,word,lang) VALUES ('276','kufr','cs');
INSERT INTO word (link,word,lang) VALUES ('277','majitel cestovní kanceláře','cs');
INSERT INTO word (link,word,lang) VALUES ('278','Podzemní','cs');
INSERT INTO word (link,word,lang) VALUES ('279','','cs');
INSERT INTO word (link,word,lang) VALUES ('280','mládežnická ubytovna','cs');
INSERT INTO word (link,word,lang) VALUES ('281','na celém světě','cs');
INSERT INTO word (link,word,lang) VALUES ('282','Ministerstvo obrany','cs');
INSERT INTO word (link,word,lang) VALUES ('283','to nevadí','cs');
INSERT INTO word (link,word,lang) VALUES ('284','to nefunguje','cs');
INSERT INTO word (link,word,lang) VALUES ('285','Řekni mi čas, prosím.','cs');
INSERT INTO word (link,word,lang) VALUES ('286','počkej','cs');
INSERT INTO word (link,word,lang) VALUES ('287','ve stejnou dobu','cs');
INSERT INTO word (link,word,lang) VALUES ('288','rozmyslím','cs');
INSERT INTO word (link,word,lang) VALUES ('289','ve středu','cs');
INSERT INTO word (link,word,lang) VALUES ('290','na cestě z ... na','cs');
INSERT INTO word (link,word,lang) VALUES ('291','Co se děje?','cs');
INSERT INTO word (link,word,lang) VALUES ('292','cítit jako doma','cs');
INSERT INTO word (link,word,lang) VALUES ('293','Prosím.','cs');
INSERT INTO word (link,word,lang) VALUES ('294','Jen se dívám','cs');
INSERT INTO word (link,word,lang) VALUES ('295','u banky','cs');
INSERT INTO word (link,word,lang) VALUES ('296','džíny','cs');
INSERT INTO word (link,word,lang) VALUES ('297','Jakou velikost jste?','cs');
INSERT INTO word (link,word,lang) VALUES ('298','Chtěli byste ...?','cs');
INSERT INTO word (link,word,lang) VALUES ('299','tady a teď','cs');
INSERT INTO word (link,word,lang) VALUES ('300','Jakou to má barvu?','cs');
INSERT INTO word (link,word,lang) VALUES ('301','stihnout letadlo','cs');
INSERT INTO word (link,word,lang) VALUES ('302','jak dlouho?','cs');
INSERT INTO word (link,word,lang) VALUES ('303','je čas jít','cs');
INSERT INTO word (link,word,lang) VALUES ('304','příští','es');

GRANT ALL ON link TO voc4u;
GRANT ALL ON word TO voc4u;
GRANT ALL ON image TO voc4u;
