ALTER TABLE link ADD COLUMN flag SMALLINT DEFAULT 0;

UPDATE link SET flag=4 WHERE link.usr=1;


ALTER TABLE usr ADD COLUMN admin SMALLINT DEFAULT 0;
UPDATE usr SET admin=1 WHERE usr.id=3;


CREATE TABLE last_visit_t (
    type INTEGER NOT NULL,
    usr INTEGER NOT NULL,
    FOREIGN KEY (usr) REFERENCES usr (id) ,
    datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(type,usr)
);


ALTER TABLE link ADD COLUMN changed TIMESTAMP DEFAULT CURRENT_TIMESTAMP;